
      backend:
  name: git-gateway
  branch: main # change to 'master' if your default branch is named master

media_folder: "assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "notices"
    label: "Notices"
    folder: "_notices"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "PDF Attachment / File", name: "file", widget: "file", required: false }
      - { label: "Notice Details", name: "body", widget: "markdown", required: false }
      
      
